version: 0.2

env:
  variables:
    APPKEY: 'test'

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      #######################################################################
      - echo :Set up environment
      #######################################################################
      - echo $(env)

  pre_build:
    commands:
      #######################################################################
      - echo :Installing dependencies
      #######################################################################
      - cd ${CODEBUILD_SRC_DIR}/frontend/web-blog
      - ls -l
      - npm install

  build:
    commands:
      #######################################################################
      - echo :Running build
      #######################################################################

  post_build:
    commands:
      #######################################################################
      - echo :Copy build folder to s3
      #######################################################################
      - cd ${CODEBUILD_SRC_DIR}/frontend
      - ls -l

      #######################################################################
      - echo :Trigger subsequent build for running end-to-end integration automation tests
      #######################################################################
